### ISSUE TITLE
Heading is not selected after clicking Ctrl + ↑ + H in code editor

### ISSUE THREAD

**Issue by saloydinovv** [Juratbek/upper_access#21]
1. Log into Upper.
2. Click on "Maqola yozish"
3. Click on + in code editor
4. Use Ctrl + ↑ + H buttons --> Opening Browser history

Expected: Heading will be selected

**Comment by Juratbek** [comment]
@saloydinovv this issue should be in upper_frontend repo

**Comment by saloydinovv** [comment]
> @saloydinovv this issue should be in upper_frontend repo

I will move it
